language: c

env:
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n conda_env python=$PYTHON_VERSION
  - conda activate conda_env
  - conda env update -f "binder/environment.yml"

script:
  - conda activate conda_env
  - python setup.py install
  - pylint anamic/
  - python -c "import anamic; anamic.run_all_tests()"
