language: python

env:
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n anamic python=$PYTHON_VERSION
  - conda activate anamic
  - conda env update -f "binder/environment.yml"

script:
  - conda activate anamic
  - python setup.py install
  - nosetests
